name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: arduino/setup-protoc@v3
    - uses: actions/checkout@v3
    - name: Build library
      run: cargo build --verbose
    - name: Build linux example
      run: cd examples/linux && cargo build --verbose
    - name: Build esp32s3 example
      run: cd examples/esp32s3 && cargo build --verbose
    # Comment unit tests because they are failing when using local files
    # TODO: fix
    # - name: Run tests
    #   run: cargo test --verbose
