name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v3
    - name: Build library
      run: cargo build --verbose
    - name: Build linux example
      run: cd examples/linux && cargo build --verbose
    - name: Setup ESP-IDF
      uses: esp-rs/xtensa-toolchain@v1.5
      with:
        default: true
        buildtargets: esp32s3
        ldproxy: true
    - name: Create secrets file
      run: |
        echo 'pub const WIFI_SSID : &str = "ssid";' > examples/esp32s3/src/secrets.rs
        echo 'pub const WIFI_PASSWORD : &str = "password";' >> examples/esp32s3/src/secrets.rs
        echo 'pub const SCURID_SERVER : &str = "192.168.99.99";' >> examples/esp32s3/src/secrets.rs
        echo 'pub const CA_CERT: &str = "";' >> examples/esp32s3/src/secrets.rs
    - name: Build esp32s3 example
      run: cd examples/esp32s3 && cargo build --verbose
    # Comment unit tests because they are failing when using local files
    # TODO: fix
    # - name: Run tests
    #   run: cargo test --verbose
